### ISSUE TITLE
Keyboard keys in the walk controller

### ISSUE THREAD

**Issue by fabienrohrer** [darwinop/webots-cross-compilation#119]
Everybody has not the luck to have page up and page down on its keyboard ^^

Choosing other keys to start/stop the walk would be better.
Maybe the space key to toggle between walk and not walk.

**Comment by DavidMansolino** [comment]
Ok,
their is just one little problem,
their is no enumeration for the space bar (like KEYBOARD_PAGEUP),
did I put the ascii code directly (32) ?

Edit : Olivier just told me tu put ' '.

**Comment by fabienrohrer** [comment]
yes, (key == ' ') should work.
