### ISSUE TITLE
darwinop at github

### ISSUE THREAD

**Issue by outchy** [darwinop/webots-cross-compilation#139]
Salut,

En effet la pollution d'un commentaire de pull-request n'est pas le meilleur endroit pour discuter de cela. Je découvre github depuis peu et je n'ai pas fait attention à l'endroit où j'ai lancé la conversation... Désolé. Peut-être qu'une "issue" séparée l'est un peu plus. L'idéal serait que github permette des forums dans l'organisation "darwinop" et pas seulement dans les sous-projets.

Donc pour revenir à mon idée initiale, le projet darwin-op sur sourceforge est inactif, j'ai rapporté une demi-douzaine de rapports de bugs et d'amélioration qui ne sont pas prises en compte (cf liens à la fin). Ces rapports ont tous un patch attaché et sont assez facilement incorporables au code principal de darwin-op. Les forums sur robotsource.org sont "juste" des fils de discussions avec aucune centralisation du code.

Il y a bien un repo SVN sur sourceforge, mais bon SVN n'est pas GIT et il n'est pas facile de gérer pleins de modifications locales tout en se maintenant syncho avec la référence. SVN ne propose pas toutes les aides que propose GIT dans ce domaine.

Donc voilà, mon idée serait de créer un nouveau projet "darwin-op" dans l'organisation "darwinop" pour y créer un repo plus "actif" et plus "réactif" que l'officiel sur sourceforge. Si ce n'est pas dans les projets des admins de votre organisation, je créerai à coté. Mais bon votre organisation a une visibilité "optimale" car elle s'appelle déjà "darwinop".
- Florent
  liens:
  http://sourceforge.net/tracker/?group_id=374584&atid=1559869&source=navbar (je suis également outchy @ sourceforge)
  http://sourceforge.net/tracker/?group_id=374584&atid=1559866&source=navbar

**Comment by fabienrohrer** [comment]
Hi again Florent,

You should use english on this project.
All DARwIn-OP contributors knows english, which is not the case of french.
I'm sure reposting the same message in english will give the answers you are looking for.

Sincerely
