### ISSUE TITLE
Kinect and Darwin-op in Webots

### ISSUE THREAD

**Issue by david781** [darwinop/webots-cross-compilation#206]
I am new to Darwin-op so I will need some help. I am trying to do imitation of darwin-op using Kinect camera. My question is how to create the motion files and integrating the Kinect and the Darwin-op/Webots. I have done the same thing using Nao robot and

**Comment by DavidMansolino** [comment]
Hi,
A motions file (containing a lot of different motions) is already distributed with Webots, but you are free to edit it or to create a new one, in order to do so, please refer to the user guide of DARwIn-OP with Webots section 3.2:
https://github.com/darwinop/webots-cross-compilation/blob/master/projects/robots/darwin-op/doc/darwin.pdf?raw=true

**Comment by david781** [comment]
I have gone through this motion file already available in the source code. I want to know how to create a motion file using the Kinect Camera and transfer this motion captured data to the webots/Darwin-OP for run-time motion creation and imitation.

**Comment by DavidMansolino** [comment]
I think the motion manager is not the best way for creating motion in rune-time,
You should probably try to act directly on the servos

**Comment by david781** [comment]
OK. Can you suggest the possible solution for relating the Kinect camera input to the servos of the robot in webots/Darwin-OP.

**Comment by fabienrohrer** [comment]
The conversion from the Kinect skeleton to DARwIn-OP may be not trivial, depending on their match (but I'm quite sure they are far to match directly).

I think that a good approach is to convert the Kinect skeleton end bones to relative positions (relative to the body origin), and then to use an inverse kinematic (IK) solver to find the corresponding DARwIn servo positions.
=> the difficult task is to introduce the DARwIn specifications into the IK solver
I think that IKfast could do the job: http://openrave.org/docs/latest_stable/openravepy/ikfast/

Sincerely,
Fabien Rohrer
