### ISSUE TITLE
segmentation fault with 'walk'controller

### ISSUE THREAD

**Issue by darwinop** [darwinop/webots-cross-compilation#216]
I believe this is due to keyboard functionality. I tried running 'soccer' (motions and walking are fine) and no problems

**Comment by fabienrohrer** [comment]
Do you mean in the new Webots 7.1.2? We have indeed an issue there.

Why do you think it's related with the keyboard functionnality?

Cheers,
Fabien

**Comment by DavidMansolino** [comment]
Just to be sure you are speaking about cross-compilation, and not about remote-control, right?

When did the segmentation fault happen? At the beginning of the controller or when using keyboard?

Best,
David

**Comment by darwinop** [comment]
solved
