### ISSUE TITLE
Controller cannot be build

### ISSUE THREAD

**Issue by arasalt** [darwinop/webots-cross-compilation#220]
Hello I'am using webots free,
Whenever I try to compile any simple code for the controller it tells me:
This evaluation version does not allow you to recompile this controller.
You can only recompile the following controllers:
- Rat0
- Rat1
- darwin-op_team_0
- darwin-op_team_1
- nao_team_0
- nao_team_1
- SampleController

However it didn't give me permission to compile  darwin-op_team_1.cpp as well.
What is the problem?

**Comment by DavidMansolino** [comment]
Dear Arasalt,

Did you open one of the worlds of robostadium (for example  WEBOTS_HOME/projects/contests/robotstadium/worlds/robotstadium_darwin-op_vs_darwin-op.wbt) and try to compile the controller?

Sincerely,
David

**Comment by fabienrohrer** [comment]
Hi,

I can't reproduce the problem.
The regular procedure is to open the contest world:
WEBOTS_HOME/projects/contests/robotstadium/worlds/robotstadium_darwin-op_vs_darwin-op.wbt
Then to select/open the darwin-op_team_1.cpp file in the Webots Text Editor, then to select Build/Build menu item.

Could you fill a bug report using the "Help|Bug report..." menu item?
It will give us you environment OS, and it is more a Webots bug than others.

Sincerely,
Fabien Rohrer
