### ISSUE TITLE
mTimeStep

### ISSUE THREAD

**Issue by ERRC** [darwinop/webots-cross-compilation#229]
Well, we actually get some DARwInOPs, and I found this site to program with WEBOTS, but I have some doubts with 3 parts of the program:
- mTimeStep
- myStep ()
- step()
  I can not understand how it works everyone, sorry I do not know if it's an innocent question, but I see that are frequently used lines. 

I hope someone can answer my questions, thanks.

**Comment by darwinop** [comment]
The file darwin.pdf located in the docs folder does a nice and concise job of explaining step(int ms), where ms is mTimeStep.

Read through it and it should make sense.

**Comment by fabienrohrer** [comment]
Nice to read you found the requested information in the documentation.

**Comment by ERRC** [comment]
Thank's I'll read again. :+1:

**Comment by DavidMansolino** [comment]
Here is the documentation folder: https://github.com/darwinop/webots-cross-compilation/tree/master/projects/robots/darwin-op/doc
