### ISSUE TITLE
webots controller python error

### ISSUE THREAD

**Issue by Eli7S** [darwinop/webots-cross-compilation#273]
INFO: my_controller: Starting controller: python.exe -u "my_controller.py" 
[my_controller] Traceback (most recent call last):
[my_controller]   File "my_controller.py", line 7, in <module>
[my_controller]     from controller import *
[my_controller]   File "C:\Program Files\Webots\lib\controller\python37\controller.py", line 15, in <module>
[my_controller]     import _controller
[my_controller] ImportError: DLL load failed: The specified module could not be found.
WARNING: 'my_controller' controller exited with status: 1.

how to fix it? i'am beginner with webots

**Comment by omichel** [comment]
answered here: https://github.com/cyberbotics/webots/issues/1344
